### ISSUE TITLE
Remove-GSGmailDelegate asking for confirmation without specifying -confirm

### ISSUE THREAD

**Issue by n-searle** [scrthq/PSGSuite#101]
Hi,

Am I missing something because I am getting a confirmation request when running Remove-GSGmailDelegate without specifying '-confirm' .

Thanks,
Neil

**Expected behavior**
Remove delegate without confirmation.

**Screenshots**
![removeconfirmation](https://user-images.githubusercontent.com/44114177/46920718-62b31300-cfea-11e8-9209-a0915a55f391.PNG)

**Environment (please complete the following information):**
 - OS:  MS Server 2012 R2
 - PowerShell Version:  Windows PowerShell 5.1
 - PSGSuite Version:  2.15.4

**Comment by scrthq** [comment]
Hi @n-searle! The default value for the `Confirm` parameter on functions that support `ShouldProcess` is `$true`, unexpectedly enough. To prevent being prompted for confirmation, you can either...

1. Run the command with `-Confirm:$false` included, i.e.:  
```powershell
Remove-GSGmailDelegate -User $user -Delegate $delegate -Confirm:$false
```
2. Or by setting `$ConfirmPreference = "None"` earlier in your script.
	* This is less desirable, in case you have another function/cmdlet being called that you may want to retain confirmation functionality on.

FYI - All of the `Remove-*` functions in PSGSuite support `ShouldProcess` (it's actually one of the things tested for during CI/CD unit testing for this module).

**Comment by scrthq** [comment]
More on ConfirmPreference here: https://blogs.msdn.microsoft.com/powershell/2006/12/14/confirmpreference/

**Comment by n-searle** [comment]
Hi,

Thanks for the quick response and indeed for the module :)

Working as expected now with -confirm:$false .

Can I make a suggestion to make the add-delegate command also support ShouldProcess.  The implications of adding access, for to example a privileged account incorrectly, is more severe than removing access.

Again thanks for the response and top work!

Neil

**Comment by scrthq** [comment]
That's perfectly fair! I'll have to plan for it, ideally supporting Should proceed on all the New-* / Add-* (where appropriate) in the 3.0.0 release

Glad you're enjoying the module!! 😁

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BarnumD** [comment]
The default Confirm:$true here seems to be backwards to all the other CMD-lets i'm used to.  Take [Set-ADUser](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-aduser?view=win10-ps) or [New-ADUser](https://docs.microsoft.com/en-us/powershell/module/addsadministration/new-aduser?view=win10-ps), they both default confirm to $false.

**Comment by scrthq** [comment]
@BarnumD - This is the default behavior for the `Confirm` parameter, PSGSuite doesn't override or set default values. The reason you may not get prompted for some cmdlets that support ShouldProcess is due to the ConfirmImpact level. If a cmdlet sets it's ConfirmImpact to something lower that the current `$ConfirmPreference` in your session and `Confirm` is `$false`, then you will not be prompted. If the cmdlet's `ConfirmImpact` level is set to the same or higher than your `$ConfirmPreference` and you don't explicitly pass `-Confirm:$false`, you will be prompted. Check out this article from Adam Bertram on the topic for more info: https://4sysops.com/archives/confirm-confirmpreference-and-confirmimpact-in-powershell/

PSGSuite may seem "backwards" as all `Remove-*` functions included have `ConfirmImpact="High"`. To prevent introducing breaking changes, only the `Remove-*` functions support ShouldProcess and have a defined Impact level. In the context of this issue, you can see those values being set on `Remove-GSGmailDelegate` here as a confirmation that this isn't breaking any standard PowerShell expectations on the functions that do implement `SupportsShouldProcess`: https://github.com/scrthq/PSGSuite/blob/master/PSGSuite/Public/Delegation/Remove-GSGmailDelegate.ps1#L22
