### ISSUE TITLE
Create new project

### ISSUE THREAD

**Issue by MichaelMc64** [scrthq/PSGSuite#116]
I ran into a problem trying to create a project following the instructions on the initial setup page. 
Being new to GSuite, I was glad to see a link to "Click here to create a new project with the following API's enabled." I clicked the link, then the Continue button, and was greeted with the message "You may not have permission to create projects in this organization. Contact your Google Apps account admin to verify you have the Project Creator role." 
Actually, I have already created two projects (one for use with GAM, and one for use with GSMME). If I click the select project drop down, then New Project, I can create a project just fine.

**Comment by scrthq** [comment]
Hey @MichaelMc64 - Are you signed into Google with multiple accounts (i.e. Personal + work?) It could be that the default account does not have permissions for some reason.

That being said, you can totally piggy back off a similar project like GAM (since PSGSuite more or less would be for the same purpose overall) and just generate the appropriate Service Account credentials.

I'll check out the quick link though and see if I can replicate and figure it out! Thanks for the tip and opening this issue!!

**Comment by scrthq** [comment]
Hey @MichaelMc64 - I'm not able to replicate this on my end. When I try, it allows me to create a project with the specified API's enabled. I've updated the docs to include your notes and workaround for those that encounter the same issue though!

**Comment by MichaelMc64** [comment]
It looks like you were correct about multiple accounts being the problem. I did have other accounts in my account list. I signed out of all accounts, then signed back in to the corporate account, and the process worked correctly. It's still not clear to me how Google or Chrome decides that an account is the "default" (I can't find any setting for this in either the Chrome or Gmail interface), rather than using the account which is currently in use in the browser. But this corrected the problem, so thanks!

**Comment by scrthq** [comment]
Strange! Yeah, sometimes Google plays nice and allows you to choose the account to complete the auth process with, other times it uses the account logged into Chrome, other times it uses the default account logged into Google Services (since that's not always the same as the account logged into Chrome). Fun times! I'm glad you're good though!
