### ISSUE TITLE
What is the intended Update-Module behavior?

### ISSUE THREAD

**Issue by phatmandrake** [scrthq/PSGSuite#126]
My existing installation of PSGsuite was done through PowerShellGet. I've used PowerShellGet to update the module; however, after the successful install, the existing configuration seemed to be ignored (Cmdlets were not showing up) until I re-ran Set-PSGsuiteConfig without targeting anything or specifying any parameters.

I'm fairly new to the limitations of PowerShellGet in general, but is it the intended behavior that running Update-Module require that you then run Set-PSGsuiteConfig?

I've looked through the wiki documentation for any information on properly updating PSGsuite, but I didn't see anything.

**Comment by scrthq** [comment]
hola, @phatmandrake! The correct/easiest way to update is by simply running `Update-Module PSGSuite`. Update-Module should allow you to update without the need to reset your PSGSuite config, since the config is stored outside the module folder. The config itself shouldn't impact importing the module or which functions are available though, it just contains the information needed for PSGSuite to build the various Service connections to Google after module import.

Cmdlets/functions not showing up is potentially indicative of something else being broken. What version of PSGSuite are you using and which functions aren't showing up as available after you import the module?

**Comment by phatmandrake** [comment]
Hmm, perhaps it was a blip. After removing the module and attempting Update-Module a few times, I'm unable to replicate the issue. I was using the Powershell Integrated Console in VSCode so this may have caused the behavioral issue.

**Comment by scrthq** [comment]
@phatmandrake odd indeed! I live in VS Code myself, so I don't think that comes into play too much, but I'm glad you're sorted regardless!
