### ISSUE TITLE
'Get-GSUserList' & 'Get-GSUser -Filter *' are "broken"

### ISSUE THREAD

**Issue by sguilbault-sherweb** [scrthq/PSGSuite#127]
**Describe the bug**
With latest version, there is no error but nothing is returned.

**To Reproduce**
1. Call Get-GSUserList

**Expected behavior**
I should have the full list of users.

**Additional context**
Not sure yet if the problem is on my side or global, would be appreciated if it can be tested by someone else to confirm the problem.

**Comment by sguilbault-sherweb** [comment]
when i call get-gsuser without params or with a given user, it work as expected.

**Comment by scrthq** [comment]
hey @sguilbault-sherweb - What are you seeing when you tack on `-Verbose` to those commands? And do you have your CustomerId added to your config?

I'm not able to reproduce on my end, here's my output for reference:

![image](https://user-images.githubusercontent.com/12724445/49469321-da244800-f7cc-11e8-9557-a85aafb4a467.png)

**Comment by sguilbault-sherweb** [comment]
I found out my problem. We recently configured a domain alias and changed all our primaryemail values to used this new domain (the rest being on the old domain).

I now need to call the cmdlets with -Domain parameter.

**Comment by sguilbault-sherweb** [comment]
Sorry for the trouble ...

**Comment by scrthq** [comment]
No trouble at all! Yeah, multi-domain can be a little odd. When you run `Get-GSUser -Filter * -Verbose`, does it show that it's `Getting all Users for Domain 'domain.com'` or `Getting all Users for Customer 'C0xxxxxx'`? Asking as you should be able to get all users for your entire customer account (i.e. all domains you own), but it may be defaulting to Domain due to config preference. If it's defaulting to domain, I have some additional steps for you that may help.

**Comment by scrthq** [comment]
Keeping this open for a moment so that we're 100% on the same page =]

**Comment by scrthq** [comment]
Here's what I would do:

1. Run: `Set-PSGSuiteConfig -Preference CustomerId -CustomerId (Get-GSUser).CustomerId`
	* This will update your Config to indicate CustomerId as your preference and set your CustomerId in your config if not already set.
2. Run: `$users = Get-GSUser -Filter * -Verbose`
	* This _should_ give you your full user list now for all domains owned by your customer.

The Preference config value tells functions like `Get-GSUser` the scope at which you'd like to perform your action if no other parameter forces the alternative. When you specify the Domain parameter for `Get-GSUser`, for example, i.e. `Get-GSUser -Filter * -Domain domain.com`, this tells PSGSuite to disregard whatever your Preference is in your config and run it at the domain scope.

For example; if you have `domain1.com` set in your config as your Domain, `Domain` set as your `Preference` and no users in `domain1.com` because they moved to `domain2.com`, then `Get-GSUser -Filter *` will not return anything (since it's only looking in `domain1.com` for users based on your config). `Get-GSUser -Filter * -Domain domain2.com` will work, because you're overriding your config values and specifying a different domain.

Let me know if that makes sense and/or if it doesn't align with what you're seeing!

**Comment by sguilbault-sherweb** [comment]
I forgot what I had put in configurations a couple weeks ago, I'll revisit my configuration file today, i was probably in domain mode so i'll switch in customer mode. Bottom line, your code is working as expected (why i had close the issue). Thanks for the hints, I'll let you know later how it goes.

**Comment by scrthq** [comment]
Got it! Just making sure you're good to.go! I'll get this closed out then, please don't hesitate to reach out if there's anything else needed!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
