### ISSUE TITLE
Incorrect parsing Attachment

### ISSUE THREAD

**Issue by wizarden1** [scrthq/PSGSuite#140]
**Describe the bug**
A lot of incorrect data with working with attachments.
When parsing mail with 2 attachments, all attachments shows as one.

it's only one message with attachment, and has 2 attachments

**To Reproduce**
```powershell
$msg = Get-GSGmailMessageList -Filter "to:me","is:unread", "has:attachment" | Get-GSGmailMessage -ParseMessage
$msg.Attachments.count
1
1
$msg.Attachments
ContentDuration         :
ContentMd5              :
ContentTransferEncoding : Base64
FileName                : xxxxx.ods
ContentObject           : MimeKit.ContentObject
Headers                 : {Content-Type: application/vnd.oasis.opendocument.spreadsheet;        name="195-formats&mapping.ods", Content-Disposition: attachment; filename="195-formats&mapping.ods", Content-Transfer-Encoding: base64, Content-ID: <f_jpo8d6ah0>...}
ContentDisposition      : Content-Disposition: attachment; filename="195-formats&mapping.ods"
ContentType             : Content-Type: application/vnd.oasis.opendocument.spreadsheet; name="195-formats&mapping.ods"
ContentBase             :
ContentLocation         :
ContentId               : f_jpo8d6ah0
IsAttachment            : True

ContentDuration         :
ContentMd5              :
ContentTransferEncoding : Base64
FileName                : (SAMPLE).csv
ContentObject           : MimeKit.ContentObject
Headers                 : {Content-Type: application/octet-stream;      name="(SAMPLE).csv", Content-Disposition: attachment;                                                                                                                                               filename="(SAMPLE).csv", Content-Transfer-Encoding: base64, Content-ID: <f_jpo8el3g1>...}
ContentDisposition      : Content-Disposition: attachment; filename="(SAMPLE).csv"
ContentType             : Content-Type: application/octet-stream; name="(SAMPLE).csv"
ContentBase             :
ContentLocation         :
ContentId               : f_jpo8el3g1
IsAttachment            : True

$msg.Attachments.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
False    False    WhereEnumerableIterator`1                System.Linq.Enumerable+Iterator`1[MimeKit.MimeEntity]
```

**To Reproduce**
Another problem

```powershell
$($(Get-GSGmailMessageList -Filter "to:me","is:unread", "has:attachment" | Get-GSGmailMessage).Payload.Parts | where {$_.Filename -like "*.csv"}).body

AttachmentId
------------
ANGjdJ9FGiRZu8ZJpAocF3MV__Yfh0hHF_mpNt3eNfXkDHCXMRyXQXL-FHEwt-6YlDR6ks1gz80cws83vzLaaWbEsi5QPRhkn_CnJ6-WdXNKYZzCisKS_quliU6SlCViDH3Euc4PUNx0gVPWP7g1QnAfXFu9kMjSgGBUC2W1XRo3XWG76G4-0Y_84B-R-YlWatKT23wePQOjqPCYkVQbrylQoR-pd6DvkUh23OWsKoikiGYIXMb0RGSx_E_RoNFj5Go8rjfKaU2Ohlku-A3Yy1crbgGF_D7lW_mi5Kcsrcrb63IP8z6pj8i9g...
```

**Expected behavior**
Get base64 data

**Environment (please complete the following information):**
 - OS:  [e.g. Windows 10 1809]
 - PowerShell Version:  5.1
 - PSGSuite Version:  2.22.0

**Comment by scrthq** [comment]
Hey @wizarden1 - For awareness, PSGSuite uses [MimeKit](http://www.mimekit.net/) to parse the raw MIME messages into objects, so outside of reinventing the wheel entirely, we'll need to work with the resulting object provided by that assembly. 

From the first example provided, you're getting back 2 attachments, but they aren't contained in an array as expected so you're getting back 2 objects with a count of `1` instead of a single array object with a count of `2`. Still getting back 2 attachments though there.

Your second example has a call to `Where-Object` that removes the attachments that aren't a CSV. Assuming that your initial call to `Get-GSGmailMessageList` yielded the same results as the first example, I would only expect to get a single AttachmentId back since your message list only contains one CSV attachment.

Let me know if I'm missing anything, but I don't see any issues here, per se.

**Comment by scrthq** [comment]
If the end goal is to be able to save the attachments to file and you don't mind saving all of the attachments, `Get-GSGmailMessage` includes the `SaveAttachmentsTo` parameter that accepts a local path to save the attachments to. You can see the code handling that here: https://github.com/scrthq/PSGSuite/blob/master/PSGSuite/Public/Gmail/Get-GSGmailMessage.ps1#L99..L109

The only thing that PSGSuite cannot _currently_ do is specify which attachments you'd like to save. If that's something you're interested in, it wouldn't be too difficult to add, just let me know.

**Comment by scrthq** [comment]
hey @wizarden1 - Going to close this out since this is a bit stale now and the issue you're having is default behavior for the 3rd party library that PSGSuite uses and doesn't have control over (MimeKit), so there's not really any actions I can take from my end to resolve without re-parsing the constructed MimeKit object and adding a ton of unwanted/unnecessary overhead within that process.
