### ISSUE TITLE
Batch Request Support

### ISSUE THREAD

**Issue by Foggy2** [scrthq/PSGSuite#151]
**Is your feature request related to a problem? Please describe.**
Currently I am using the Calendar API functions to publish timetables to staff/student calendars within our school. With over 1000 staff/students publishing timetables in this manner for an entire school term (~10 weeks) results in ~350,000 individual calendar events.
Dealing with this many calendars/events has some obvious performance considerations, so I am looking for ways that performance may be able to be improved.

**Describe the solution you'd like**
Today I stumbled upon requesting batching on the API reference. From what I understand, I believe that this could be a simple way to improve performance when working with much large numbers of calendars/events.
So if it is possible I would like to explore the use of request batching with the Calendar API functions.
https://developers.google.com/calendar/batch
https://developers.google.com/api-client-library/dotnet/guide/batch

**Describe alternatives you've considered**
My current solution is to run multiple threads via the use of Runspaces however, if the performance improvements of batching is considerable that could be a simpler solution going forward.

**Comment by scrthq** [comment]
Hey @Foggy2 - Batch requests can be a little messy to handle internally from PSGSuite, since it requires the batching to be done in in the original request, which may not apply to all situations. The route I take personally is similar to what you're doing, I'm just using `PoshRSJob` to multithread big jobs as needed. Submitting a batch request is handled asynchronously as well, so handling monitoring for individual request success/failure within the batch request is it's own can of worms. 

Implementing batch requests in PSGSuite would likely run into the following design decision: Do we choose to...

1. ... not to monitor the status of the async requests?
    * Pros
        * Fast, since the code is not waiting for the completion of the requests in the batch at all
    * Cons
        * Error prone, since you're not monitoring for success or failure of the individual requests in the batch
2. ... hold the command open after submitting the batch request to monitor all batched requests for completion?
    * Pros
        * Individual requests retain visibility and can be handled as such
    * Cons
        * Slower, since you're back to waiting for completion of each request in the batch

IMHO, keeping the multithreading/batch requests external to PSGSuite itself retains simplicity and standardizes user experience across functions. This also enables you to manage your own rate limiting if needed and leverage your preferred multi-threading solution overall.

If you have any ideas on how to approach it, I'm all ears!

**Comment by scrthq** [comment]
The other part to keep in mind with batch requests is that you have to use a single service object to create the batch request with. What this means for APIs like Calendar, Gmail, and Drive that need to impersonate the user is that all of your requests in that batch would need to be targeting that user.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Foggy2** [comment]
Hey @scrthq. Sorry for the delay in responding.

Thanks for your detailed response it actually made quite a bit of sense! With the points you have raised I can't see any justifiable reason to pursue the idea any further as I must agree with you at this point that it would be much simpler to remain using multiple threads where appropriate.

Thanks also for the tip of PoshRSJob, I have had a quick look at it and it looks quite a bit nicer than what I have been using so far.

I don't think there is much more discussion to be had on this topic so feel free to close the issue.

Lastly thanks again for your ongoing assistance these last couple of months. PSGSuite has been a huge help as we start to use G-Suite more in our school.

**Comment by scrthq** [comment]
No worries on the delay! I'm glad we're on the same page and I'm stoked as always that PSGSuite is working wonders for you too!

Closing this out, don't hesitate to open any more if needed!

Cheers! ❤️
