### ISSUE TITLE
[System.IO.FileShare] does not contain a method named 'op_Addition'

### ISSUE THREAD

**Issue by lefoimpeur** [scrthq/PSGSuite#178]
I have another similar issue with "Start-GSDriveFileUpload" :
`Start-GSDriveFileUpload : Method invocation failed because [System.IO.FileShare] does not contain a method named 'op_Addition'`

**Comment by scrthq** [comment]
Thanks for letting me know, @lefoimpeur ! Couple questions so I can dig in a little better:

* What's the full command you're running? Feel free to replace anything sensitive with a dummy variable value.
* Does the command fail immediately or does it appear to be working then fail after some time?
* How many files are you trying to upload at once or is this a single file?

**Comment by lefoimpeur** [comment]
- Full command : `Start-GSDriveFileUpload -Path $Export_File -Parents $Destination_Folder_ID -Wait`
- Fail immediately
- Only one file

**Comment by scrthq** [comment]
Thank you for the additional details, @lefoimpeur !! Should have a fix for you by tomorrow night once I have some time =]

**Comment by lefoimpeur** [comment]
Hi @scrthq,
Did you have time to work on the fix ?

**Comment by scrthq** [comment]
hey @lefoimpeur - I have the fix for this sorted =], just working on getting a couple other pending fixes/features included that have been delaying this overall. Should hopefully have a new version published tonight with this fix, I'll definitely let you know though!

For reference, the issue is that PS4 doesn't handle adding the enum values for `[System.IO.FileShare]`. You can replicate the error with the following line, fixed line right after for comparison (validated fix in my PS2.0 VM):

```powershell
# Current code (works fine in PS5+)
[System.IO.FileShare]::Delete + [System.IO.FileShare]::ReadWrite

# Updating to the following (works in PS2.0+)
[System.IO.FileShare]"Delete, ReadWrite"
```

**Comment by scrthq** [comment]
Hey @lefoimpeur - v2.26.2 is out now with this fix. Please try it out and let me know if you're still having any issues! Thanks for your patience!

**Comment by lefoimpeur** [comment]
Hi @scrthq , really good, It works !
Thank you
