### ISSUE TITLE
get-gsdrivefilelist returns error

### ISSUE THREAD

**Issue by jparodi** [scrthq/PSGSuite#259]
when running `get-gsdrivefileinfo` and other gsdrive cmdlets, error is received 

> You cannot call a method on a null-valued expression.

This occurs even when providing my own account as the target, or no account at all (which should default to my user)

Error occurs in version 2.34.0 and I have not tried older

**Comment by jparodi** [comment]
Error seems to resolved itself after updating to v2.35.1 and restarting my session

**Comment by scrthq** [comment]
Hey @jparodi - thanks for using PSGSuite and opening up an issue! Just a heads up, this usually happens if the underlying assemblies aren't loaded correctly, e.g. if the module was autoimported by calling one of the functions vs explicitly imported before via `Import-Module PSGSuite`

In case anyone stumbles across this issue, I wanted to provide the same background info 🙂
